# 1. Introduction to NumPy and Array Creation

In [1]:
arr1 = [10, 20, 30, 40, 50]
arr1

[10, 20, 30, 40, 50]

In [6]:
import numpy as np
arr = np.zeros((2,3),dtype = int)
print(arr)



[[0 0 0]
 [0 0 0]]


In [11]:
a = np.linspace(0,100,5)
print(a)

[  0.  25.  50.  75. 100.]


# 2. Array Indexing and Slicing

In [12]:
arr1D = [10, 20, 30, 40, 50]
arr1D[:3]

[10, 20, 30]

In [17]:
s = slice(1,5,2)
arr1D[s]

[20, 40]

In [18]:
arr1D[3] = 50
arr1D

[10, 20, 30, 50, 50]

# 3.Reshaping Arrays

In [21]:
arr1D = np.arange(12)
print(arr1D)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
arr2D = arr1D.reshape(3,4)
print(arr2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 4.Broadcasting and Element-wise operations

In [25]:
arr1D = [1,2,3,4,5]
arr1D

[1, 2, 3, 4, 5]

In [29]:
p = [10]
np.add(arr1D, p)

array([11, 12, 13, 14, 15])

In [30]:
q = [3]
np.multiply(arr1D, 3)

array([ 3,  6,  9, 12, 15])

In [31]:
np.square(arr1D)

array([ 1,  4,  9, 16, 25])

# 5. Basic Statistics with Arrays

In [40]:
temp = np.array([30,32,31,29,28,33,34])
mean_temp = temp.sum(axis=0) / temp.size
print(mean_temp)

31.0


In [47]:
max_temp = temp.max()
min_temp = temp.min()
print("Minimum temperature: ", min_temp, "\nMaximum temperature: ", max_temp)

Minimum temperature:  28 
Maximum temperature:  34


In [48]:
total_temp = temp.sum()
print("Total Sum of temperature: ", total_temp)

Total Sum of temperature:  217


# 6. Real-World problem: Sales Analysis

In [53]:
Products = np.array([[200,220,250,270,300],
                    [150,160,170,180,200]])
print("Total sales for product 1 and product 2 are", Products.sum(axis=1), "respectively")

Total sales for product 1 and product 2 are [1240  860] respectively


In [76]:
average_sales_per_day = Products.mean(axis=0)
print("Average sales per day:", average_sales_per_day)

Average sales per day: [175. 190. 210. 225. 250.]


In [78]:
days_with_highest_sales = Products.argmax(axis=1)
print("Day with the highest sales for each product: ", days_with_highest_sales+1)

Day with the highest sales for each product:  [5 5]
